PlateFormeBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: PlateFormeBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        contenu:
            type: text
        actif:
            type: boolean

    oneToMany:
        enfant:
            targetEntity: PlateFormeBundle\Entity\Post
            mappedBy: parent
    manyToOne:
        parent:
            targetEntity: PlateFormeBundle\Entity\Post
            inversedBy: enfant
        categorie:
            targetEntity: PlateFormeBundle\Entity\CategoriePlateforme
        user:
            targetEntity: UserBundle\Entity\User


    lifecycleCallbacks: {  }