CalendarBundle\Entity\Agenda:
    type: entity
    table: null
    repositoryClass: CalendarBundle\Repository\AgendaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        start:
            type: datetime
        end:
            type: datetime
        titre:
            type: string
            length: 255
        texte:
            type: text
        lieu:
            type: string
            length: 255
        color:
            type: string
            length: 255
            nullable: true
        slider:
            type: boolean
            nullable: true
        lien:
            type: text
            nullable: true

    manyToOne:
        image:
            targetEntity: HarasBundle\Entity\Media
            cascade: ['all']
    lifecycleCallbacks: {  }
